/* glossary-data.js — every term students need, by unit, for the Glossary tab
   (glossary.js) and site search (search.js). Rows are [topic, term, definition].
   Add a row here and it shows up in the unit's Glossary AND in search.
   Keep definitions to 1–2 plain sentences; the term's slug (its #g- anchor)
   comes from the term text, so renaming a term changes its link. */
window.GLOSSARY = {
1: [
  ["1.1","Song Dynasty","Chinese dynasty (960–1279) that ruled through a Confucian bureaucracy and built one of the world's most commercialized, urbanized, and technologically advanced economies."],
  ["1.1","Civil Service Exam","Merit-based test on the Confucian classics used to select government officials; it created the scholar-gentry and allowed limited social mobility."],
  ["1.1","Scholar-gentry","Educated class of Confucian officials who staffed the Chinese bureaucracy and became China's most powerful social group."],
  ["1.1","Confucianism","Chinese philosophy stressing social harmony through proper relationships, hierarchy, filial piety, and moral, educated leadership."],
  ["1.1","Neo-Confucianism","Song-era revival of Confucianism that absorbed Buddhist and Daoist ideas; it reinforced hierarchy, filial piety, and patriarchy and spread to Korea, Japan, and Vietnam."],
  ["1.1","Filial Piety","The Confucian duty of children to honor and obey parents and ancestors; it was the model for loyalty to rulers."],
  ["1.1","Buddhism","Religion founded by Siddhartha Gautama teaching that suffering ends through the Eightfold Path; it spread across Asia and changed as it did (Mahayana in East Asia, Theravada in Southeast Asia)."],
  ["1.1","Champa Rice","Fast-ripening, drought-resistant rice from Vietnam that let Song farmers harvest more often, boosting China's food supply and population."],
  ["1.1","Grand Canal","Vast inland waterway linking northern and southern China that moved grain and goods and integrated China's internal markets."],
  ["1.1","Foot binding","Painful practice of binding elite girls' feet to keep them small; a status symbol that limited women's mobility and reflected Song patriarchy."],
  ["1.1","Tributary System","Chinese diplomatic and trade order in which neighboring states acknowledged China's superiority with gifts (tribute) in exchange for trade rights and recognition."],
  ["1.1","Paper Money","Currency first widely used in Song China; with credit instruments like flying cash, it supported a booming commercial economy."],
  ["1.1","Proto-industrialization","Large-scale production before mechanized factories, such as Song China's enormous iron and steel output and its porcelain and silk workshops."],
  ["1.1","Sinification","Adoption of Chinese culture (writing, Confucianism, Buddhism, bureaucracy) by neighboring societies such as Korea, Japan, and Vietnam."],
  ["1.1","Shogun","Military ruler of feudal Japan who held real power while the emperor remained a religious figurehead."],
  ["1.1","Samurai","Japanese warrior class bound by loyalty to regional lords (daimyo) under a code of honor later called bushido."],
  ["1.2","Dar al-Islam","'House of Islam': the lands under Muslim rule or where Islam was widely practiced, stretching from Spain and West Africa to South and Southeast Asia."],
  ["1.2","Islam","Monotheistic religion founded by Muhammad in 7th-century Arabia, based on the Quran and the Five Pillars; divided into Sunni and Shia branches."],
  ["1.2","Caliphate","An Islamic state ruled by a caliph, the political and religious successor to Muhammad."],
  ["1.2","Abbasid Caliphate","Islamic dynasty (750–1258) centered in Baghdad; a golden age of learning, it weakened over time and fell to the Mongols in 1258."],
  ["1.2","House of Wisdom","Abbasid center of learning in Baghdad where scholars translated Greek, Persian, and Indian texts and advanced math, astronomy, and medicine."],
  ["1.2","Nasir al-Din al-Tusi","Persian scholar whose advances in mathematics and astronomy built on Greek and Indian learning and later influenced European astronomers."],
  ["1.2","Seljuk Turks","Turkic Muslim group that took control of much of the Abbasid lands in the 1000s, ruling as sultans while the caliph kept only religious authority."],
  ["1.2","Mamluks","Enslaved Turkic soldiers who seized power in Egypt and ruled their own sultanate (1250–1517); they halted the Mongols at Ain Jalut in 1260."],
  ["1.2","Delhi Sultanate","Turkic Muslim state (1206–1526) ruling a Hindu-majority northern India; it brought Islamic culture and architecture to South Asia."],
  ["1.2","Sharia","Islamic law drawn from the Quran and the sayings of Muhammad, governing religious practice and daily life."],
  ["1.2","Sufism","Mystical form of Islam emphasizing a personal connection with God; Sufi missionaries adapted Islam to local customs and helped it spread."],
  ["1.2","Jizya","Tax on non-Muslims living under Muslim rule; paying it let them practice their own religion."],
  ["1.2","Madrasa","Islamic school of higher learning that trained scholars in religion, law, and the sciences."],
  ["1.2","Al-Andalus","Muslim-ruled Iberia (Spain); cities like Córdoba were centers of learning where Muslims, Christians, and Jews exchanged ideas."],
  ["1.3","Hinduism","South Asian religion with many gods, organized around dharma (duty), karma, reincarnation, and the caste system."],
  ["1.3","Caste System","Hindu social hierarchy of hereditary groups that determined a person's occupation, marriage, and status."],
  ["1.3","Bhakti Movement","Hindu devotional movement stressing personal love for a single god and rejecting caste barriers; it appealed to women and lower castes."],
  ["1.3","Vijayanagara Empire","Powerful Hindu kingdom in southern India (1336–1646) that resisted the Delhi Sultanate and grew rich from Indian Ocean trade."],
  ["1.3","Rajput Kingdoms","Hindu warrior kingdoms in northwest India that resisted the Delhi Sultanate."],
  ["1.3","Srivijaya","Buddhist maritime empire on Sumatra that grew rich by controlling the Strait of Malacca and taxing Indian Ocean shipping."],
  ["1.3","Majapahit","Hindu-Buddhist sea-based kingdom on Java that dominated Southeast Asian trade in the 1300s."],
  ["1.3","Khmer Empire (Angkor)","Southeast Asian land-based empire (in modern Cambodia) whose capital Angkor had massive temples and irrigation works."],
  ["1.3","Angkor Wat","Enormous Khmer temple complex, first Hindu and later Buddhist; a symbol of religious syncretism in Southeast Asia."],
  ["1.3","Theravada Buddhism","Older, more monastic branch of Buddhism that became dominant in Sri Lanka and mainland Southeast Asia."],
  ["1.3","Urdu","Language that blended Persian, Arabic, and Hindi, created as Muslim rulers interacted with Indian populations."],
  ["1.3","Syncretism","The blending of different religious or cultural traditions into something new, such as Islam adapting to local customs in South and Southeast Asia."],
  ["1.4","Maya","Mesoamerican civilization of competing city-states known for its calendar, writing, and astronomy; it had declined by 1200 but its culture survived."],
  ["1.4","Mexica (Aztec) Empire","Mesoamerican empire centered at Tenochtitlan that expanded through warfare and demanded tribute and captives for human sacrifice."],
  ["1.4","Tenochtitlan","Island capital of the Mexica (Aztec) Empire in Lake Texcoco, one of the largest cities in the world c. 1500."],
  ["1.4","Chinampas","Floating gardens built in the lakes around Tenochtitlan that allowed intensive farming to feed a huge urban population."],
  ["1.4","Aztec Tribute","Goods, labor, and captives that conquered peoples had to deliver to the Mexica; it funded the empire but bred resentment the Spanish later exploited."],
  ["1.4","Inca Empire","Andean empire centered at Cusco that controlled millions of people through a centralized bureaucracy, roads, and labor obligations."],
  ["1.4","Mit'a System","Inca labor obligation requiring communities to work a set number of days on state projects such as roads, mines, and farms."],
  ["1.4","Quipu","Knotted cords the Inca used to keep records of taxes, population, and goods."],
  ["1.4","Qhapaq Ñan (Inca Roads)","The Inca road network of roughly 25,000 miles that tied the empire together for armies, messengers, and administrators."],
  ["1.4","Terrace Farming","Carving mountainsides into flat steps to grow crops, used by the Inca in the Andes."],
  ["1.4","Cahokia","Largest city of the Mississippian mound-building culture (near modern St. Louis), with a powerful chiefdom and huge earthen mounds."],
  ["1.5","Mali Empire","West African empire (c. 1235–1600) that grew rich controlling the trans-Saharan gold and salt trade; its rulers were Muslim."],
  ["1.5","Mansa Musa","Mali's most famous ruler, whose 1324 pilgrimage to Mecca displayed the empire's gold so lavishly it caused inflation in Cairo."],
  ["1.5","Sundiata","Founder of the Mali Empire (c. 1235), remembered through oral epics told by griots."],
  ["1.5","Swahili City-States","Independent East African trading cities (Kilwa, Mombasa, Mogadishu) that blended Bantu and Arab cultures through Indian Ocean trade."],
  ["1.5","Great Zimbabwe","Southern African state famous for its stone walls, which grew wealthy trading gold and ivory to the Swahili coast."],
  ["1.5","Griots","West African oral historians and storytellers who preserved history, genealogy, and tradition."],
  ["1.5","Ethiopia (Solomonic Dynasty)","Christian kingdom in East Africa that claimed descent from King Solomon; known for rock-cut churches such as those at Lalibela."],
  ["1.5","Hausa Kingdoms","City-states in West Africa (modern northern Nigeria) that grew through trade and adopted Islam."],
  ["1.6","Feudalism","European political system in which kings granted land to lords in exchange for military service and loyalty."],
  ["1.6","Manorialism","European economic system in which serfs worked a lord's land in exchange for protection and a plot to farm."],
  ["1.6","Serfs","Peasants legally bound to the land who owed labor and part of their harvest to the lord of the manor."],
  ["1.6","Roman Catholic Church","The dominant institution of Western Europe, which shaped politics, education, and daily life and united Europeans culturally."],
  ["1.6","Great Schism","The 1054 split of Christianity into the Roman Catholic Church in the West and the Eastern Orthodox Church in the East."],
  ["1.6","Crusades","Religious wars (1095–1291) in which European Christians tried to capture the Holy Land; they increased European contact with Muslim trade and learning."],
  ["1.6","Three-Field System","Crop rotation method that left only one-third of land fallow, raising European food production and population."],
  ["1.6","Black Death","Bubonic plague pandemic of the mid-1300s that killed about one-third of Europe; the labor shortage weakened serfdom and feudalism."],
  ["1.6","Bourgeoisie","In medieval Europe, the new middle class of merchants and artisans living in growing towns."],
  ["1.6","Magna Carta","1215 English document that limited the king's power and protected nobles' rights; an early step toward limited government."],
  ["1.6","Renaissance","Revival of classical Greek and Roman learning and art that began in Italy in the 1300s–1400s, fueled by trade wealth."]
],
2: [
  ["2.1","Silk Roads","Network of overland trade routes across Central Asia linking China to the Middle East and Europe; carried luxury goods, religions, technology, and disease."],
  ["2.1","Luxury Goods","High-value, lightweight goods such as silk, porcelain, and spices that were worth carrying long distances on the Silk Roads."],
  ["2.1","Caravanserai","Roadside inns spaced along trade routes that gave merchants and their camels food, water, and shelter, and became places of cultural exchange."],
  ["2.1","Flying Cash","Chinese paper credit that let merchants deposit money in one place and withdraw it in another."],
  ["2.1","Bills of Exchange","Written orders to pay a sum at a distant place, used by merchants so they did not have to carry large amounts of coin."],
  ["2.1","Banking Houses","Institutions that stored money, lent funds, and issued credit, making long-distance trade easier."],
  ["2.1","Money Economy","Shift toward using currency and credit rather than barter, expanding commerce along trade routes."],
  ["2.1","Samarkand","Central Asian oasis city (modern Uzbekistan) that thrived as a hub of Silk Road trade and cultural exchange."],
  ["2.1","Kashgar","Oasis city in western China where Silk Road routes met, a key stop for caravans."],
  ["2.1","Porcelain","Fine ceramic produced in China, one of the most sought-after luxury exports along the Silk Roads and sea routes."],
  ["2.1","Junk Ship","Large Chinese ship with watertight compartments and a stern rudder, used for long-distance trade."],
  ["2.2","Mongol Empire","Largest contiguous land empire in history, built by Genghis Khan and his successors in the 1200s; it connected Eurasia under one power."],
  ["2.2","Genghis Khan","Mongol leader (Chinggis Khan) who united the Mongol tribes in 1206 and began conquests across Asia using mobile cavalry and terror."],
  ["2.2","Nomadic Pastoralism","A way of life based on herding animals and moving seasonally, the basis of Mongol society and military skill."],
  ["2.2","Khanate","One of the four regional states the Mongol Empire split into after Genghis Khan's death."],
  ["2.2","Pax Mongolica","'Mongol Peace': the period when Mongol control made Eurasian trade routes safer, boosting trade and cultural exchange."],
  ["2.2","Yam System","Mongol relay system of postal stations that moved messages, officials, and merchants quickly across the empire."],
  ["2.2","Yuan Dynasty","Mongol dynasty in China (1271–1368) founded by Kublai Khan; it kept Chinese officials at arm's length and used foreigners in government."],
  ["2.2","Kublai Khan","Grandson of Genghis Khan who conquered the Song and founded the Yuan Dynasty in China."],
  ["2.2","Il-Khanate","Mongol khanate in Persia that sacked Baghdad (1258), later converted to Islam and adopted Persian culture."],
  ["2.2","Golden Horde","Mongol khanate in Russia that collected tribute from Russian princes, helping Moscow rise as its tax collector."],
  ["2.2","Chagatai Khanate","Mongol khanate in Central Asia that controlled key stretches of the Silk Roads."],
  ["2.2","White Lotus Society","Chinese Buddhist secret society that led rebellions against Mongol (Yuan) rule, helping bring the Ming to power."],
  ["2.2","Ming Dynasty","Chinese dynasty (1368–1644) that overthrew the Mongol Yuan, restored Confucian rule, and sponsored Zheng He's voyages."],
  ["2.2","Mongol Transfer of Knowledge","Mongol movement of scholars and ideas across Eurasia, spreading Greek and Islamic medicine, astronomy, and the Uyghur script."],
  ["2.3","Indian Ocean Trade","Sea-based trade network linking East Africa, Arabia, India, Southeast Asia, and China; the largest trade network of the era."],
  ["2.3","Monsoon Winds","Seasonal winds that reverse direction twice a year, letting sailors plan round-trip voyages across the Indian Ocean."],
  ["2.3","Lateen Sail","Triangular sail that let ships sail against the wind; common on Arab dhows."],
  ["2.3","Astrolabe","Instrument that measured the angle of stars to find a ship's latitude, refined by Muslim scholars."],
  ["2.3","Magnetic Compass","Chinese invention that showed direction using a magnetized needle, making open-sea navigation possible."],
  ["2.3","Stern Rudder","Chinese steering device mounted at the back of the ship that made large vessels easier to control."],
  ["2.3","Dhow","Arab sailing ship with lateen sails, widely used in Indian Ocean trade."],
  ["2.3","Diasporic Communities","Groups of merchants living far from their homeland (such as Arabs in East Africa or Chinese in Southeast Asia) who spread their culture and married locals."],
  ["2.3","Swahili City-States","East African coastal trading cities like Kilwa and Mombasa that became wealthy trading gold and ivory; their Swahili language blended Bantu and Arabic."],
  ["2.3","Kilwa","One of the richest Swahili city-states, which controlled gold exports from Great Zimbabwe."],
  ["2.3","Melaka (Malacca)","Southeast Asian port-state that controlled the Strait of Malacca, grew rich taxing shipping, and converted to Islam."],
  ["2.3","Zheng He","Ming admiral who led seven huge treasure-fleet voyages (1405–1433) to Southeast Asia, India, Arabia, and East Africa to display Chinese power and collect tribute."],
  ["2.3","Treasure Fleets","The massive Ming fleets commanded by Zheng He; the Ming ended them in 1433 and turned inward."],
  ["2.4","Trans-Saharan Trade","Trade across the Sahara Desert linking West Africa to North Africa and the Mediterranean, mainly gold, salt, and enslaved people."],
  ["2.4","Camel Saddle","Improved saddle that let camels carry heavier loads, making large-scale desert caravans possible."],
  ["2.4","Camel Caravans","Large groups of traders and camels crossing the Sahara together for protection and efficiency."],
  ["2.4","Gold-Salt Trade","Exchange of West African gold for Saharan salt, the economic core of trans-Saharan trade."],
  ["2.4","Ghana Empire","Early West African trading empire that taxed the gold-salt trade before declining in the 1000s."],
  ["2.4","Mali Empire","West African empire that grew rich taxing trans-Saharan trade; its Muslim rulers built mosques and schools."],
  ["2.4","Mansa Musa","Ruler of Mali whose 1324 pilgrimage to Mecca displayed Mali's wealth and connected it to the wider Islamic world."],
  ["2.4","Sundiata","Founder of the Mali Empire (c. 1235)."],
  ["2.4","Timbuktu","Mali city that became a major center of trade and Islamic scholarship, famous for its libraries and Sankore mosque."],
  ["2.5","Cultural Diffusion","The spread of ideas, beliefs, and technologies from one society to another, often along trade routes."],
  ["2.5","Neo-Confucianism","Revived Confucianism that spread from China to Korea, Japan, and Vietnam through trade and diplomacy."],
  ["2.5","Spread of Islam","Islam spread along trade routes to West Africa, East Africa, and Southeast Asia through merchants and Sufi missionaries rather than conquest."],
  ["2.5","Gunpowder","Chinese invention that spread west along trade routes and transformed warfare across Eurasia."],
  ["2.5","Paper and Printing","Chinese papermaking and printing technologies that spread through the Islamic world to Europe."],
  ["2.5","Arabic Numerals","Number system developed in India and spread by Muslim scholars and merchants, later adopted in Europe."],
  ["2.5","Ibn Battuta","Moroccan Muslim scholar who traveled about 75,000 miles across Dar al-Islam (1325–1354) and wrote about the societies he visited."],
  ["2.5","Marco Polo","Venetian merchant who traveled to Yuan China; his account increased European interest in Asian trade."],
  ["2.5","Margery Kempe","English Christian mystic whose pilgrimages to Jerusalem and Rome were recorded in one of the first autobiographies in English."],
  ["2.5","Rabban Sauma","Christian monk from Mongol China who traveled to Persia and Europe as a diplomat for the Il-Khanate."],
  ["2.6","Champa Rice","Fast-ripening rice from Vietnam that spread through China, allowing more harvests and population growth."],
  ["2.6","Bananas","Crop carried from Southeast Asia to East Africa by Indian Ocean traders, which improved diets and spurred population growth."],
  ["2.6","Citrus","Fruits spread by Muslim traders from South Asia into the Mediterranean world."],
  ["2.6","Bubonic Plague","Disease spread by fleas on rats along trade routes; as the Black Death (1340s) it killed millions across Eurasia and North Africa."],
  ["2.6","Urbanization","Growth of cities; trade-hub cities like Hangzhou, Cairo, and Samarkand grew, while plague and war caused others to decline."],
  ["2.6","Hangzhou","Southern Song capital and one of the world's largest, richest cities, fed by trade and the Grand Canal."],
  ["2.6","Venice","Italian city-state that grew rich as the European end point of Mediterranean trade in Asian goods."]
],
3: [
  ["3.1","Gunpowder Empires","The Ottoman, Safavid, and Mughal empires, which used cannons and muskets to conquer and control vast territory."],
  ["3.1","Ottoman Empire","Sunni Muslim Turkish empire (c. 1300–1922) that captured Constantinople in 1453 and dominated the eastern Mediterranean, Balkans, and Middle East."],
  ["3.1","Fall of Constantinople (1453)","Ottoman capture of the Byzantine capital using massive cannons; it became Istanbul, the Ottoman capital."],
  ["3.1","Mehmed II","Ottoman sultan who conquered Constantinople in 1453."],
  ["3.1","Suleiman the Magnificent","Ottoman sultan (r. 1520–1566) under whom the empire reached its height; known in the empire as 'the Lawgiver.'"],
  ["3.1","Safavid Empire","Shia Muslim Persian empire (1501–1736), founded by Shah Ismail, that rivaled the Sunni Ottomans and Mughals."],
  ["3.1","Battle of Chaldiran (1514)","Ottoman victory over the Safavids using gunpowder weapons; it fixed the Sunni–Shia frontier between the empires."],
  ["3.1","Mughal Empire","Muslim empire (1526–1857) ruling a Hindu-majority India; at its height under Akbar it was one of the richest states in the world."],
  ["3.1","Babur","Central Asian ruler descended from Timur and Genghis Khan who founded the Mughal Empire in 1526."],
  ["3.1","Qing (Manchu) Dynasty","Last Chinese dynasty (1644–1912), founded by the Manchus from the north, who expanded China into Taiwan, Mongolia, Tibet, and Central Asia."],
  ["3.1","Russian Empire","Empire that expanded from Moscow across Siberia and toward the Black Sea and Baltic under tsars such as Ivan IV and Peter the Great."],
  ["3.1","Tokugawa Shogunate","Military government that unified Japan (1603–1868), centralized control over the daimyo, and later restricted foreign contact."],
  ["3.1","Songhai Empire","West African Muslim empire that succeeded Mali and controlled trans-Saharan trade until Moroccan gunpowder armies defeated it in 1591."],
  ["3.2","Bureaucracy","A system of government officials organized in ranks to carry out the ruler's policies and collect taxes."],
  ["3.2","Devshirme","Ottoman system of taking Christian boys from the Balkans, converting them to Islam, and training them as soldiers or officials loyal only to the sultan."],
  ["3.2","Janissaries","Elite Ottoman infantry recruited through the devshirme and trained with gunpowder weapons."],
  ["3.2","Zamindars","Mughal landholders who collected taxes from peasants for the state and kept a share for themselves."],
  ["3.2","Tax Farming","System in which the state sold the right to collect taxes to private individuals, who kept whatever they collected above the set amount."],
  ["3.2","Salaried Samurai","Tokugawa policy that turned samurai into paid officials living in castle towns, weakening regional warrior power."],
  ["3.2","Alternate Attendance","Tokugawa rule forcing daimyo to live every other year in Edo and leave their families there, keeping them loyal and in debt."],
  ["3.2","Tribute System","Qing practice of requiring neighboring states to send gifts and acknowledge the emperor's superiority in exchange for trade."],
  ["3.2","Divine Right","Belief that a monarch's authority comes directly from God, so subjects must obey."],
  ["3.2","Mandate of Heaven","Chinese belief that heaven grants rulers the right to rule as long as they govern justly; the Qing used it to legitimize their rule."],
  ["3.2","Art and Architecture as Legitimacy","Rulers built grand monuments, palaces, and mosques to display power and divine favor."],
  ["3.2","Taj Mahal","Marble tomb built by Mughal emperor Shah Jahan, a showcase of Mughal wealth and Indo-Islamic architecture."],
  ["3.2","Versailles","Louis XIV's lavish palace outside Paris, where nobles were kept close and busy, displaying the king's absolute power."],
  ["3.2","Kangxi Emperor","Long-ruling Qing emperor who expanded the empire and embraced Confucian scholarship to win over the Chinese elite."],
  ["3.2","Peter the Great","Russian tsar (r. 1682–1725) who westernized Russia, built a modern army and navy, and founded St. Petersburg."],
  ["3.2","Legitimize","To make a ruler's power seem rightful and accepted, through religion, monuments, ceremonies, or law."],
  ["3.2","Consolidate","To strengthen and centralize control over territory already gained, such as through bureaucracies, taxes, and loyal militaries."],
  ["3.3","Sunni-Shia Rivalry","Religious and political conflict between Sunni Ottomans and Shia Safavids, fought partly at the Battle of Chaldiran."],
  ["3.3","Sunni Islam","The majority branch of Islam, which holds that leaders should be chosen by the community; the faith of the Ottomans and Mughals."],
  ["3.3","Shia Islam","Branch of Islam holding that leadership belongs to Ali's descendants; made the state religion of Safavid Persia."],
  ["3.3","Akbar","Mughal emperor (r. 1556–1605) who promoted religious tolerance, abolished the jizya, married Hindu princesses, and included Hindus in government."],
  ["3.3","Din-i Ilahi","Akbar's blended faith combining elements of Islam, Hinduism, and other religions; it did not outlast him."],
  ["3.3","Jizya","Tax on non-Muslims; Akbar abolished it, while Aurangzeb brought it back."],
  ["3.3","Aurangzeb","Mughal emperor (r. 1658–1707) who enforced strict Islam, reinstated the jizya, and destroyed temples, provoking revolts that weakened the empire."],
  ["3.3","Sikhism","Monotheistic religion founded by Guru Nanak in Punjab, blending Hindu and Islamic ideas and rejecting caste."],
  ["3.3","Guru Nanak","Founder of Sikhism (1469–1539)."],
  ["3.3","Protestant Reformation","16th-century movement, begun by Martin Luther in 1517, that challenged the Catholic Church and split Western Christianity."],
  ["3.3","Martin Luther","German monk whose Ninety-Five Theses (1517) attacked the sale of indulgences and launched the Reformation."],
  ["3.3","Indulgences","Payments to the Catholic Church to reduce punishment for sins; their sale sparked Luther's protest."],
  ["3.3","Catholic Counter-Reformation","The Catholic Church's response to Protestantism: the Council of Trent, the Jesuits, and reforms to fix abuses."],
  ["3.3","Council of Trent","Catholic meeting (1545–1563) that reaffirmed Catholic doctrine and reformed church abuses."],
  ["3.3","Jesuits","Catholic religious order founded in 1540 that ran schools and sent missionaries around the world."],
  ["3.3","Thirty Years' War","Religious and political war (1618–1648) between Catholic and Protestant states that devastated Central Europe."],
  ["3.4","Absolutism","System in which a monarch holds total power, unchecked by nobles or parliaments, often justified by divine right."],
  ["3.4","Louis XIV","French 'Sun King' (r. 1643–1715), the model absolute monarch, who said 'I am the state.'"],
  ["3.4","Methods of Legitimizing Power","Religion, monumental architecture, ceremonies, and art that rulers used to justify their authority."]
],
4: [
  ["4.1","Caravel","Small, fast Portuguese ship with lateen and square sails that could sail against the wind and explore coastlines."],
  ["4.1","Carrack","Larger ocean-going ship with more cargo space, used for long voyages and trade."],
  ["4.1","Fluyt","Dutch cargo ship that needed a small crew and carried large loads, lowering shipping costs."],
  ["4.1","Astrolabe","Navigation tool, refined by Muslim scholars, that measured latitude using the stars."],
  ["4.1","Lateen Sail","Triangular sail, borrowed from Indian Ocean sailors, that let ships sail against the wind."],
  ["4.1","Magnetic Compass","Chinese navigation tool that showed direction on the open sea."],
  ["4.1","Portolan Charts","Detailed sailing maps showing coastlines and ports, which improved European navigation."],
  ["4.1","Cartography","Mapmaking; improved maps helped Europeans plan and repeat ocean voyages."],
  ["4.2","Motives for Exploration","'God, gold, and glory': spreading Christianity, finding wealth and trade routes to Asian spices, and gaining national prestige."],
  ["4.2","Reconquista","The Christian reconquest of Iberia from Muslim rulers, completed in 1492; it fueled Spain's crusading, expansionist spirit."],
  ["4.2","Prince Henry the Navigator","Portuguese prince who sponsored navigation schools and voyages down Africa's coast in the 1400s."],
  ["4.2","Bartolomeu Dias","Portuguese explorer who rounded the Cape of Good Hope in 1488."],
  ["4.2","Vasco da Gama","Portuguese explorer who reached India by sailing around Africa in 1498, opening a sea route to Asian trade."],
  ["4.2","Christopher Columbus","Italian explorer sailing for Spain who reached the Caribbean in 1492, beginning lasting contact between Europe and the Americas."],
  ["4.2","Ferdinand Magellan","Portuguese explorer sailing for Spain whose expedition (1519–1522) was the first to circumnavigate the globe."],
  ["4.2","Treaty of Tordesillas (1494)","Agreement dividing newly claimed lands between Spain and Portugal along a line, giving Portugal Brazil and Africa-to-Asia routes."],
  ["4.2","Northwest Passage","A hoped-for sea route through North America to Asia; its search led English, French, and Dutch explorers to claim North American lands."],
  ["4.3","Columbian Exchange","Transfer of plants, animals, people, and diseases between the Eastern and Western hemispheres after 1492."],
  ["4.3","Smallpox","Old World disease that killed a huge share of Indigenous Americans, who had no immunity."],
  ["4.3","New World Crops","Crops from the Americas like potatoes, maize, and cassava that spread worldwide and fueled population growth in Europe, Africa, and Asia."],
  ["4.3","Old World Crops and Animals","Wheat, rice, sugarcane, horses, cattle, and pigs brought to the Americas, transforming diets and landscapes."],
  ["4.3","Cash Crops","Crops grown for sale and profit rather than for local use, such as sugar, tobacco, and cotton."],
  ["4.3","Sugar Plantations","Large farms growing sugarcane for export, first in Brazil and the Caribbean; they drove demand for enslaved African labor."],
  ["4.3","Environmental Change","Deforestation, soil depletion, and new species introduced to the Americas by plantations and livestock."],
  ["4.4","Conquistadors","Spanish soldiers and explorers who conquered the Americas, aided by disease, steel, horses, and Indigenous allies."],
  ["4.4","Hernán Cortés","Spanish conquistador who conquered the Aztec Empire (1519–1521) with the help of Indigenous allies and smallpox."],
  ["4.4","Francisco Pizarro","Spanish conquistador who conquered the Inca Empire in the 1530s, taking advantage of civil war and disease."],
  ["4.4","Trading Post Empire","Portuguese strategy of controlling trade through fortified coastal posts (like Goa and Malacca) rather than conquering large territories."],
  ["4.4","Dutch East India Company (VOC)","Dutch joint-stock company that dominated the spice trade in Indonesia, with its own army and power to make treaties."],
  ["4.4","British East India Company","English joint-stock company that traded in India and later took political control there."],
  ["4.4","Manila Galleons","Spanish ships that carried American silver across the Pacific to Manila, exchanging it for Chinese silk and porcelain (1565–1815)."],
  ["4.4","Kingdom of Kongo","Central African kingdom whose rulers converted to Christianity and traded with Portugal, including in enslaved people."],
  ["4.4","Asante and Dahomey","West African states that grew powerful by selling enslaved captives to Europeans in exchange for guns."],
  ["4.4","Atlantic Slave Trade","Forced transport of about 12 million Africans to the Americas (1500s–1800s) to work mainly on plantations."],
  ["4.4","Middle Passage","The deadly voyage of enslaved Africans across the Atlantic in crowded, brutal conditions."],
  ["4.5","Encomienda","Spanish system granting colonists the right to Indigenous labor and tribute in exchange for 'protecting' and converting them."],
  ["4.5","Hacienda","Large Spanish colonial estate producing crops and livestock, worked by Indigenous and mixed-race laborers."],
  ["4.5","Mit'a / Coerced Labor","Spanish adaptation of the Inca mit'a that forced Indigenous men to work in silver mines like Potosí."],
  ["4.5","Chattel Slavery","System in which enslaved people are treated as property that can be bought and sold, and slavery is inherited."],
  ["4.5","Potosí","Massive silver mine in the Andes (modern Bolivia); its silver flooded the global economy."],
  ["4.5","Silver Trade","Flow of American silver to Europe and China, where demand was huge; it linked the world economy."],
  ["4.5","Single Whip Reform","Ming tax reform requiring taxes to be paid in silver, which drove China's demand for American silver."],
  ["4.5","Mercantilism","Economic policy that a nation grows rich by exporting more than it imports and using colonies for raw materials and markets."],
  ["4.5","Joint-Stock Company","Business owned by many investors who share profits and risk, such as the VOC and British East India Company."],
  ["4.5","Triangular Trade","Atlantic trade pattern: manufactured goods to Africa, enslaved people to the Americas, raw materials to Europe."],
  ["4.6","Indigenous Resistance","Revolts by Indigenous peoples against colonial rule, such as the Pueblo Revolt."],
  ["4.6","Pueblo Revolt (1680)","Uprising of the Pueblo people that drove the Spanish out of New Mexico for over a decade."],
  ["4.6","Maroon Communities","Settlements of escaped enslaved Africans in remote areas of the Americas, such as in Jamaica and Brazil."],
  ["4.6","Queen Nzinga","Ruler of Ndongo and Matamba (Angola) who resisted Portuguese expansion for decades through war and diplomacy."],
  ["4.6","Fronde","Series of revolts (1648–1653) by French nobles against the growing power of the monarchy."],
  ["4.6","Cossacks","Frontier warriors who helped Russia expand into Siberia but also rebelled against the tsars."],
  ["4.6","Sakoku","Tokugawa Japan's 'closed country' policy that expelled most foreigners, banned Christianity, and limited trade to the Dutch and Chinese at Nagasaki."],
  ["4.6","Canton System","Qing policy limiting European trade to the single port of Canton (Guangzhou) under strict control."],
  ["4.7","Casta System","Spanish colonial racial hierarchy ranking people by ancestry, with Europeans at the top and Indigenous and African people at the bottom."],
  ["4.7","Peninsulares","People born in Spain or Portugal living in the colonies; the top of the casta system."],
  ["4.7","Creoles","People of European descent born in the Americas; wealthy but below peninsulares in status."],
  ["4.7","Mestizo","Person of mixed European and Indigenous ancestry."],
  ["4.7","Mulatto","Person of mixed European and African ancestry."],
  ["4.8","Syncretic Religions","Faiths blending African, Indigenous, and Christian traditions, such as Vodou and Santería."],
  ["4.8","Virgin of Guadalupe","Image of Mary appearing to an Indigenous man in Mexico (1531); a symbol of blended Catholic and Indigenous faith."],
  ["4.8","New Global Economy","The first truly global trade network after 1500, linking all inhabited continents through silver, sugar, and slaves."]
],
5: [
  ["5.1","The Enlightenment","18th-century intellectual movement that used reason to question tradition, religion, and absolute rule, inspiring revolutions."],
  ["5.1","Scientific Revolution","16th–17th-century shift toward observation, experiment, and reason to explain the natural world (Copernicus, Galileo, Newton)."],
  ["5.1","John Locke","English philosopher who argued people have natural rights to life, liberty, and property, and may overthrow governments that violate them."],
  ["5.1","Natural Rights","Rights people are born with that governments cannot take away, such as life, liberty, and property."],
  ["5.1","Social Contract","Idea that governments get their power from the consent of the people, who agree to be governed in exchange for protection of their rights."],
  ["5.1","Jean-Jacques Rousseau","Enlightenment thinker who argued government should follow the 'general will' of the people."],
  ["5.1","Montesquieu","Enlightenment thinker who proposed separating government power into branches to prevent tyranny."],
  ["5.1","Voltaire","French Enlightenment writer who championed freedom of speech and religious tolerance."],
  ["5.1","Deism","Belief that God created the universe but does not intervene in it; popular among Enlightenment thinkers."],
  ["5.1","Mary Wollstonecraft","English writer who argued in A Vindication of the Rights of Woman (1792) that women deserve education and equal rights."],
  ["5.1","Olympe de Gouges","French writer of the Declaration of the Rights of Woman (1791), demanding equal rights for women during the French Revolution."],
  ["5.1","Seneca Falls Convention (1848)","First U.S. women's rights convention, which demanded voting rights for women."],
  ["5.1","Abolitionism","Movement to end the slave trade and slavery, driven by Enlightenment and religious ideals and slave resistance."],
  ["5.1","Abolition of Serfdom (1861)","Russian tsar Alexander II's emancipation of the serfs, part of a wave of reforms ending coerced labor."],
  ["5.2","Nationalism","Loyalty and devotion to a nation of people with a shared language, culture, and history, often wanting their own state."],
  ["5.2","American Revolution","Revolt (1775–1783) of 13 British colonies that created the United States, justified by Enlightenment ideas of natural rights."],
  ["5.2","Declaration of Independence (1776)","Document drawing on Locke to declare that people have unalienable rights and may abolish unjust governments."],
  ["5.2","French Revolution","Revolution (1789–1799) that overthrew the French monarchy and spread ideas of liberty, equality, and popular sovereignty."],
  ["5.2","Declaration of the Rights of Man and of the Citizen","1789 French document proclaiming equality before the law, popular sovereignty, and natural rights for men."],
  ["5.2","Popular Sovereignty","The idea that government's authority comes from the people."],
  ["5.2","Haitian Revolution","Revolt of enslaved people in French Saint-Domingue (1791–1804) that created Haiti, the first Black republic and first nation to abolish slavery."],
  ["5.2","Toussaint L'Ouverture","Formerly enslaved leader of the Haitian Revolution."],
  ["5.2","Latin American Revolutions","Independence movements (1808–1826), led mostly by Creole elites, that freed most of Latin America from Spain and Portugal."],
  ["5.2","Simón Bolívar","Creole leader who liberated much of northern South America; his Jamaica Letter (1815) called for independence and unity."],
  ["5.2","Túpac Amaru II","Indigenous leader of a large 1780 revolt against Spanish rule in Peru."],
  ["5.2","Unification of Germany and Italy","Nationalist movements that united many small states into Italy (1861) and Germany (1871)."],
  ["5.2","Otto von Bismarck","Prussian chancellor who unified Germany in 1871 through 'blood and iron' wars."],
  ["5.2","Propaganda Movement","Filipino reform movement led by José Rizal calling for rights under Spanish rule, a forerunner of Philippine nationalism."],
  ["5.2","Zionism","Nationalist movement, founded by Theodor Herzl in the 1890s, calling for a Jewish homeland in Palestine."],
  ["5.3","Industrial Revolution","Shift from hand production to machine and factory production that began in Britain around 1750."],
  ["5.3","Why Britain First","Britain led industrialization thanks to coal and iron, rivers and ports, colonies for raw materials and markets, banks, and a growing labor supply."],
  ["5.3","Agricultural Revolution","Improvements in farming (crop rotation, new tools, enclosure) that produced more food with fewer workers, freeing labor for factories."],
  ["5.3","Enclosure Movement","Fencing off common lands into private farms in Britain, pushing rural people to cities to work in factories."],
  ["5.3","Cottage Industry","Pre-industrial system in which families produced goods like textiles at home for merchants."],
  ["5.3","Factory System","Production in large buildings using machines, specialized labor, and strict schedules."],
  ["5.3","Textile Industry","The first industry to mechanize, turning raw cotton into cloth with machines like the spinning jenny and power loom."],
  ["5.4","Industrialization Spreads","Industrialization spread from Britain to Western Europe, the U.S., Russia, and Japan in the 1800s."],
  ["5.4","Meiji Restoration","1868 restoration of imperial rule in Japan that launched rapid, state-led industrialization and Westernization."],
  ["5.4","Deindustrialization","Decline of traditional manufacturing, as in India and Egypt, when cheap factory goods from industrial nations flooded their markets."],
  ["5.5","Steam Engine","Engine powered by burning coal to make steam, improved by James Watt; it powered factories, trains, and ships."],
  ["5.5","Railroads","Steam-powered rail lines that moved goods and people quickly and cheaply over land."],
  ["5.5","Steamships","Steam-powered ships that made ocean travel faster and more reliable, independent of winds."],
  ["5.5","Telegraph","Device that sent messages over wires with electrical signals, allowing near-instant long-distance communication."],
  ["5.5","Second Industrial Revolution","Later phase of industrialization (c. 1870–1914) based on steel, chemicals, electricity, and oil."],
  ["5.5","Bessemer Process","Method for mass-producing cheap, strong steel."],
  ["5.5","Internal Combustion Engine","Engine burning gasoline or oil; it led to cars, trucks, and planes."],
  ["5.6","State-Sponsored Industrialization","Government-led efforts to industrialize, such as in Meiji Japan, Muhammad Ali's Egypt, and Russia."],
  ["5.6","Muhammad Ali (Egypt)","Ruler of Egypt (1805–1848) who built state-owned textile factories and a modern army, though his efforts had limited success."],
  ["5.6","Laissez-faire","Economic idea that governments should not interfere in the economy."],
  ["5.6","Adam Smith","Scottish economist whose The Wealth of Nations (1776) argued free markets and competition create wealth."],
  ["5.7","Capitalism","Economic system based on private ownership, free markets, and profit."],
  ["5.7","Transnational Corporation","Company operating in many countries, such as HSBC and Unilever."],
  ["5.7","Stock Market","Place where shares of companies are bought and sold, letting businesses raise capital."],
  ["5.7","Limited Liability Corporation","Business structure in which investors can only lose what they invested, encouraging investment."],
  ["5.8","Karl Marx","German philosopher who wrote The Communist Manifesto (1848) with Friedrich Engels, arguing workers would overthrow capitalism."],
  ["5.8","Communism / Marxism","Marx's theory that class struggle between workers (proletariat) and owners (bourgeoisie) would end in a classless society with shared property."],
  ["5.8","Proletariat","In Marxist theory, the industrial working class that sells its labor to survive."],
  ["5.8","Bourgeoisie","In Marxist theory, the capitalist class that owns factories and the means of production."],
  ["5.8","Socialism","System in which the community or state owns major industries to distribute wealth more equally."],
  ["5.8","Utopian Socialism","Early socialism that tried to create ideal cooperative communities, such as Robert Owen's New Lanark."],
  ["5.8","Labor Unions","Organizations of workers that bargained for better pay, hours, and conditions, sometimes through strikes."],
  ["5.8","Luddites","English workers who smashed machines that threatened their jobs in the early 1800s."],
  ["5.8","Tanzimat Reforms","Ottoman reforms (1839–1876) modernizing law, the military, and education along Western lines."],
  ["5.8","Reform Acts","Laws in Britain and elsewhere that expanded voting rights and limited child labor and working hours."],
  ["5.9","Middle Class","Growing class of managers, professionals, and shop owners who gained wealth and influence from industrialization."],
  ["5.9","Working Class","Factory and mine workers who faced long hours, low pay, and dangerous conditions."],
  ["5.9","Urbanization","Rapid growth of cities as people moved to work in factories."],
  ["5.9","Tenements","Crowded, unsanitary apartment buildings where many urban workers lived."],
  ["5.9","Cult of Domesticity","Middle-class ideal that women belonged in the home as wives and mothers (separate spheres)."],
  ["5.10","Global Economic Integration","The growing connection of world economies through trade, investment, and industrial demand for raw materials in the 1800s."]
],
6: [
  ["6.1","Social Darwinism","Misapplication of Darwin's natural selection to human societies; 'survival of the fittest' was used to justify imperial conquest of 'inferior' peoples."],
  ["6.1","White Man's Burden","Phrase from Rudyard Kipling's 1899 poem presenting colonialism as a moral duty to 'civilize' non-Western peoples."],
  ["6.1","Civilizing Mission","Justification (French mission civilisatrice) that imperial powers had a duty to spread their culture, language, and institutions to 'less advanced' peoples."],
  ["6.1","Scientific Racism","Pseudoscientific claims about racial biology used to justify racial hierarchy and imperial conquest."],
  ["6.1","Jules Ferry","French prime minister who argued 'superior races' had a duty to civilize and that colonies were needed for French markets and prestige."],
  ["6.1","Cecil Rhodes","British businessman and colonial leader in southern Africa who dreamed of a 'Cape-to-Cairo' British Africa."],
  ["6.1","Nationalism (Imperial Motive)","National pride and rivalry that pushed European powers to compete for colonies as symbols of greatness."],
  ["6.2","New Imperialism","The wave of European, American, and Japanese expansion (c. 1870–1914) driven by industrial needs for raw materials and markets."],
  ["6.2","Berlin Conference (1884–85)","Meeting of European powers that set rules for dividing Africa without any African representatives."],
  ["6.2","Scramble for Africa","Rapid European colonization of nearly all of Africa between 1880 and 1914."],
  ["6.2","Congo Free State","King Leopold II of Belgium's personal colony, notorious for brutal forced labor in rubber collection."],
  ["6.2","British Raj","Direct British government rule over India (1858–1947) after the Indian Rebellion ended East India Company rule."],
  ["6.2","Meiji Restoration (1868)","Japan's rapid modernization that turned it into an industrial and imperial power that took Taiwan (1895) and Korea (1910)."],
  ["6.2","Protectorate","Territory with its own ruler but controlled by an outside power in foreign affairs and trade."],
  ["6.2","Sphere of Influence","Area where a foreign power holds exclusive trade and investment rights, as in China."],
  ["6.2","Extraterritoriality","Right of foreigners to be tried in their own country's courts, not local ones."],
  ["6.2","Indirect Rule","Colonial method of governing through local rulers and elites, used by the British in Africa and India."],
  ["6.2","Settler Colony","Colony where large numbers of colonizers settled permanently, such as Australia, South Africa, and Algeria."],
  ["6.2","Spanish-American War (1898)","War in which the U.S. took the Philippines, Puerto Rico, and Guam, becoming an imperial power."],
  ["6.3","Anti-Imperial Resistance","Armed revolts, religious movements, and new state-building efforts by colonized peoples against imperial rule."],
  ["6.3","Indian Rebellion of 1857","Sepoy Mutiny: revolt by Indian soldiers and civilians against the British East India Company; it led to direct British rule."],
  ["6.3","Battle of Adwa (1896)","Ethiopian victory over Italy under Menelik II that preserved Ethiopia's independence."],
  ["6.3","Zulu Wars (1879)","Conflict in which the Zulu Kingdom fought the British in southern Africa before being defeated."],
  ["6.3","Boxer Rebellion (1900)","Anti-foreign uprising in China that was crushed by an international army, further weakening the Qing."],
  ["6.3","Taiping Rebellion","Massive Chinese civil war (1850–1864) led by Hong Xiuquan against the Qing; tens of millions died."],
  ["6.3","Self-Strengthening Movement","Qing effort (1860s–1890s) to adopt Western military technology while keeping Confucian values; it had limited success."],
  ["6.3","Maji Maji Rebellion (1905–07)","Revolt in German East Africa against forced cotton growing, brutally crushed."],
  ["6.3","Ghost Dance","Native American religious movement in the 1890s that promised the return of lands and removal of settlers."],
  ["6.3","Xhosa Cattle-Killing Movement","1856–57 prophecy-driven movement in southern Africa in which the Xhosa killed their cattle hoping to drive out the British; it caused famine."],
  ["6.3","Cherokee Nation","Native American nation that built a constitutional government and written language to resist removal by the U.S."],
  ["6.3","Accommodation","Adapting to or cooperating with imperial powers, rather than resisting them outright."],
  ["6.4","Industrial Capitalism","Economic system in which industrial nations sought raw materials and markets abroad, driving imperialism."],
  ["6.4","Free Trade Imperialism","Using economic power, rather than direct rule, to open markets and control trade."],
  ["6.4","Railroad Imperialism","Building railroads in colonies to extract raw materials and move troops."],
  ["6.4","Monoculture","Dependence on a single crop or export, making colonial economies vulnerable."],
  ["6.4","Commodity Crops","Crops like cotton, rubber, palm oil, and sugar grown for export to industrial nations."],
  ["6.4","Export Enclave Economy","Economy focused on producing raw materials for export, often with foreign ownership."],
  ["6.4","Rubber","Raw material from the Congo and Amazon essential for industrial machines and tires; its extraction brought brutal forced labor."],
  ["6.4","Guano","Bird droppings used as fertilizer, exported from Peru and the Pacific islands for industrial agriculture."],
  ["6.5","Opium Wars","Wars (1839–42, 1856–60) in which Britain forced China to allow opium trade and open ports."],
  ["6.5","Lin Zexu","Qing official who destroyed British opium in 1839, sparking the First Opium War."],
  ["6.5","Treaty of Nanjing (1842)","Treaty ending the First Opium War, giving Britain Hong Kong and forcing China to open ports."],
  ["6.5","Unequal Treaties","Treaties forced on China, Japan, and others granting foreigners special privileges."],
  ["6.5","Most-Favored Nation Status","Treaty clause giving a country any trade privileges granted to others."],
  ["6.5","Gunboat Diplomacy","Using naval power to force another country into agreements."],
  ["6.5","Informal Empire","Economic control without formal political rule, like British and U.S. influence in Latin America."],
  ["6.5","Banana Republics","Latin American countries whose economies and politics were dominated by foreign fruit companies exporting a single crop."],
  ["6.6","Push Factors","Conditions driving people to leave their homeland, such as famine, poverty, and persecution."],
  ["6.6","Pull Factors","Conditions attracting migrants to a new place, such as jobs, land, and freedom."],
  ["6.6","Indentured Servitude","Contract labor in which workers agreed to work for several years in exchange for passage and wages, as with Indian laborers in the Caribbean."],
  ["6.6","Coolie Labor","Term for Chinese and Indian contract laborers who worked on plantations, mines, and railroads abroad."],
  ["6.6","Chain Migration","When migrants move to where family or community members have already settled."],
  ["6.6","Great Famine (1845–52)","Irish Potato Famine that killed about one million and pushed millions to emigrate."],
  ["6.7","Chinese Exclusion Act (1882)","U.S. law banning Chinese immigration, driven by racism and labor competition."],
  ["6.7","White Australia Policy","Australian laws limiting non-European immigration."],
  ["6.7","Nativism","Hostility toward immigrants and favoring native-born residents."],
  ["6.7","Ethnic Enclaves","Neighborhoods where migrants kept their culture, like Chinatowns and Little Italys."],
  ["6.7","Diaspora","Communities of people living outside their homeland."],
  ["6.7","Cultural Syncretism","Blending of immigrant culture with local culture."],
  ["6.7","Remittances","Money migrants send home to their families."],
  ["6.8","Formal vs. Informal Empire","Formal empire means direct political control (colonies); informal empire means economic dominance without direct rule."]
],
7: [
  ["7.1","Qing Dynasty Decline","The Qing weakened from internal rebellion and foreign pressure and collapsed in the 1911 revolution."],
  ["7.1","Chinese Revolution of 1911","Revolution led by Sun Yat-sen that overthrew the Qing and made China a republic."],
  ["7.1","Sun Yat-sen","Chinese nationalist who led the 1911 revolution and founded the Nationalist Party (Guomindang)."],
  ["7.1","Ottoman Collapse","The 'sick man of Europe' lost territory for decades and was dismantled after WWI, replaced by the Republic of Turkey in 1923."],
  ["7.1","Mexican Revolution","Revolt (1910–1920) against dictator Porfirio Díaz over land and inequality, led by figures like Zapata and Villa."],
  ["7.1","Meiji Restoration","1868 modernization of Japan from a feudal state into an industrial and military power."],
  ["7.1","Racial Equality Proposal (1919)","Japan's rejected proposal at the Paris Peace Conference to recognize racial equality."],
  ["7.2","MAIN (WWI Causes)","Militarism, Alliances, Imperialism, and Nationalism, the four long-term causes of WWI."],
  ["7.2","Militarism","Glorifying military power and building up armies and navies, as in the Anglo-German naval race."],
  ["7.2","Alliance System","Web of defensive alliances that turned a regional conflict into a world war."],
  ["7.2","Triple Entente","Alliance of Britain, France, and Russia in WWI."],
  ["7.2","Triple Alliance (Central Powers)","Germany, Austria-Hungary, and later the Ottoman Empire in WWI (Italy left the Triple Alliance to join the Allies)."],
  ["7.2","Assassination of Franz Ferdinand","1914 killing of Austria-Hungary's heir by a Serbian nationalist, the spark of WWI."],
  ["7.3","Total War","War in which nations mobilize their entire economies, populations, and resources."],
  ["7.3","Trench Warfare","WWI fighting from defensive trenches, leading to stalemate and huge casualties."],
  ["7.3","New Military Technology","Machine guns, poison gas, tanks, and airplanes that made WWI deadlier than earlier wars."],
  ["7.3","WWI Propaganda","Government messaging to build support, recruit soldiers, and demonize the enemy."],
  ["7.3","British Press Censorship (WWI)","British government control of news to maintain morale during WWI."],
  ["7.3","Colonial Troops","Soldiers from colonies, like Indian sepoys and Senegalese troops, who fought for European powers in WWI."],
  ["7.3","Russian Revolution (1917)","Overthrow of the tsar followed by the Bolshevik seizure of power, leading to the Soviet Union."],
  ["7.3","Vladimir Lenin","Bolshevik leader who led the 1917 Communist revolution and founded the Soviet state."],
  ["7.4","Great Depression","Worldwide economic collapse after 1929 that caused mass unemployment and political extremism."],
  ["7.4","Keynesian Economics","John Maynard Keynes's theory that government spending can end depressions."],
  ["7.4","New Deal","FDR's U.S. programs of government spending, jobs, and regulation to fight the Depression."],
  ["7.4","Five Year Plans","Stalin's plans for rapid state-directed Soviet industrialization."],
  ["7.4","Collectivization","Stalin's forced merging of private farms into state-controlled collective farms, causing famine."],
  ["7.4","Joseph Stalin","Soviet dictator (1924–1953) who ruled through terror, forced industrialization, and collectivization."],
  ["7.4","Economic Nationalism","Policies protecting a nation's economy, like high tariffs."],
  ["7.5","Treaty of Versailles (1919)","Treaty ending WWI that punished Germany with territory loss, reparations, and a war-guilt clause."],
  ["7.5","Fourteen Points","Woodrow Wilson's plan for peace, including self-determination and a League of Nations."],
  ["7.5","League of Nations","International organization created after WWI to keep the peace; weak without the U.S."],
  ["7.5","Self-Determination","The right of a people to choose their own government."],
  ["7.5","Mandate System","League of Nations system giving Britain and France control of former Ottoman and German territories."],
  ["7.5","Balfour Declaration (1917)","British statement supporting a Jewish homeland in Palestine."],
  ["7.5","Indian National Congress","Indian nationalist party that led the independence movement."],
  ["7.5","Mohandas Gandhi","Leader of Indian independence who used nonviolent civil disobedience (satyagraha)."],
  ["7.5","Salt March (1930)","Gandhi's protest walk to the sea to make salt, defying the British salt monopoly."],
  ["7.5","Ho Chi Minh","Vietnamese nationalist and communist leader who fought French colonial rule."],
  ["7.5","Mustafa Kemal (Ataturk)","Founder of modern Turkey who secularized and westernized the nation."],
  ["7.5","May Fourth Movement (1919)","Chinese protests against the Treaty of Versailles that sparked Chinese nationalism."],
  ["7.5","Stab-in-the-Back Legend","False German claim that the army lost WWI because of betrayal by Jews and socialists."],
  ["7.6","Fascism","Authoritarian nationalism glorifying the state, the military, and a single leader while crushing opposition."],
  ["7.6","Benito Mussolini","Fascist dictator of Italy (1922–1943)."],
  ["7.6","Adolf Hitler","Nazi dictator of Germany (1933–1945) whose aggression started WWII in Europe and who directed the Holocaust."],
  ["7.6","Lebensraum","Hitler's goal of seizing 'living space' in Eastern Europe for Germans."],
  ["7.6","Appeasement","Giving in to an aggressor's demands to avoid war, as Britain and France did with Hitler."],
  ["7.6","Munich Agreement (1938)","Deal letting Hitler annex the Sudetenland; the high point of appeasement."],
  ["7.6","Japanese Imperialism","Japan's expansion into Manchuria (1931) and China (1937) for resources and empire."],
  ["7.6","Axis Powers","Germany, Italy, and Japan in WWII."],
  ["7.6","Allied Powers","Britain, France, the Soviet Union, the U.S., and China in WWII."],
  ["7.7","Blitzkrieg","'Lightning war': fast German attacks using tanks and planes."],
  ["7.7","Total War Mobilization (WWII)","Full economic and social mobilization for WWII, including women in factories."],
  ["7.7","Soviet Propaganda Posters","Soviet art used to rally the population for the war effort."],
  ["7.7","Island Hopping","U.S. strategy in the Pacific of capturing key islands to approach Japan."],
  ["7.7","Firebombing","Bombing cities with incendiary weapons, as in Dresden and Tokyo."],
  ["7.7","Atomic Bomb (1945)","U.S. atomic bombings of Hiroshima and Nagasaki that ended WWII."],
  ["7.8","Genocide","Deliberate killing of a large group of people based on their ethnicity, nationality, race, or religion."],
  ["7.8","Holocaust","Nazi genocide of six million Jews and millions of others."],
  ["7.8","Armenian Genocide","Ottoman killing of about one million Armenians during WWI."],
  ["7.8","Holodomor","Soviet-caused famine in Ukraine (1932–33) that killed millions."],
  ["7.8","Rape of Nanjing (1937)","Mass murder and rape of Chinese civilians by Japanese troops."],
  ["7.8","Khmer Rouge","Cambodian communist regime (1975–79) under Pol Pot that killed about 1.7 million people."],
  ["7.8","Rwandan Genocide (1994)","Mass killing of Tutsi by Hutu extremists, about 800,000 in 100 days."],
  ["7.8","UNESCO Statement on Race (1949)","UN statement rejecting scientific racism after WWII."]
],
8: [
  ["8.1","Superpowers","The U.S. and USSR, which emerged as dominant rivals after WWII."],
  ["8.1","Yalta Conference","1945 meeting of Roosevelt, Churchill, and Stalin to plan postwar Europe."],
  ["8.1","United Nations","International organization founded in 1945 to maintain peace and security."],
  ["8.2","Cold War","Global rivalry (1947–1991) between the capitalist U.S. and communist USSR, fought through arms races, proxy wars, and propaganda rather than direct war."],
  ["8.2","Iron Curtain","Churchill's term for the division of Europe between the communist East and the democratic West."],
  ["8.2","Truman Doctrine","1947 U.S. policy of aiding countries resisting communism."],
  ["8.2","Containment","U.S. strategy to stop the spread of communism."],
  ["8.2","Marshall Plan","U.S. aid program to rebuild Western Europe after WWII."],
  ["8.2","NATO","Western military alliance founded in 1949."],
  ["8.2","Warsaw Pact","Soviet-led military alliance of Eastern Europe founded in 1955."],
  ["8.2","Arms Race","Competition to build more and more powerful nuclear weapons."],
  ["8.2","Mutually Assured Destruction","The idea that nuclear war would destroy both sides, deterring its use."],
  ["8.2","Cuban Missile Crisis (1962)","Standoff over Soviet missiles in Cuba, the closest the world came to nuclear war."],
  ["8.2","Space Race","U.S.-Soviet competition in space, begun with Sputnik (1957)."],
  ["8.2","Berlin Wall","Wall built in 1961 dividing East and West Berlin; a symbol of the Cold War."],
  ["8.2","Non-Aligned Movement","Nations that refused to side with either superpower."],
  ["8.2","Bandung Conference","1955 meeting of Asian and African nations that promoted non-alignment."],
  ["8.3","Proxy War","Conflict in which superpowers back opposing sides without fighting each other directly."],
  ["8.3","Korean War","1950–53 war between communist North Korea and South Korea, backed by the U.S. and UN."],
  ["8.3","Vietnam War","War in which the U.S. fought to stop communist North Vietnam from unifying Vietnam; it ended in communist victory in 1975."],
  ["8.3","Angolan Civil War","Proxy war in Angola (1975–2002) between Soviet/Cuban-backed and U.S./South African-backed groups."],
  ["8.3","Military-Industrial Complex","Alliance of the military and weapons industries, warned about by Eisenhower."],
  ["8.4","Chinese Communist Revolution","Mao Zedong's Communists won China's civil war in 1949."],
  ["8.4","Mao Zedong","Leader of Communist China (1949–1976)."],
  ["8.4","Great Leap Forward","Mao's plan (1958–62) to rapidly industrialize China, causing a famine that killed millions."],
  ["8.4","Cultural Revolution","Mao's campaign (1966–76) to purge capitalist and traditional elements, using Red Guards."],
  ["8.4","Land Redistribution","Taking land from wealthy landlords and giving it to peasants."],
  ["8.4","Cuban Revolution","Fidel Castro's 1959 overthrow of Batista, which made Cuba a communist ally of the USSR."],
  ["8.5","Decolonization","The process by which colonies gained independence after WWII."],
  ["8.5","Indian National Congress","Party that led Indian independence."],
  ["8.5","Negotiated Independence","Independence achieved through negotiation, like India and Ghana."],
  ["8.5","Armed Struggle for Independence","Independence won through violent conflict, like Algeria and Vietnam."],
  ["8.5","Muslim League","Party that pushed for a separate Muslim state (Pakistan)."],
  ["8.5","Partition of India","1947 division of British India into India and Pakistan, causing mass migration and violence."],
  ["8.5","Kwame Nkrumah","Leader who won Ghana's independence in 1957, the first in sub-Saharan Africa, and promoted Pan-Africanism."],
  ["8.5","Pan-Africanism","Movement for unity and solidarity among all Africans and people of African descent."],
  ["8.5","Algerian War","Violent struggle (1954–62) for independence from France."],
  ["8.5","Mau Mau Uprising","Kenyan revolt against British rule in the 1950s."],
  ["8.5","Dien Bien Phu (1954)","Vietnamese victory that ended French rule in Indochina."],
  ["8.6","Newly Independent States","Countries that became independent after decolonization."],
  ["8.6","State-Guided Economic Development","Government-directed economic planning, as in India and Egypt."],
  ["8.6","Gamal Abdel Nasser","Egyptian leader who nationalized the Suez Canal (1956) and promoted Arab nationalism."],
  ["8.6","Suez Crisis (1956)","Britain, France, and Israel invaded Egypt after Nasser nationalized the canal; U.S. and Soviet pressure forced them out."],
  ["8.6","Creation of Israel (1948)","Founding of Israel, followed by war with Arab neighbors and the displacement of Palestinians."],
  ["8.6","Postcolonial Migration","Migration from former colonies to former colonial powers, like South Asians to Britain."],
  ["8.7","Nonviolent Resistance","Peaceful protest methods like boycotts and civil disobedience."],
  ["8.7","Civil Rights Movement","U.S. movement led by Martin Luther King Jr. to end segregation and racial discrimination."],
  ["8.7","Apartheid","South Africa's system of legal racial segregation (1948–1994)."],
  ["8.7","Nelson Mandela","Anti-apartheid leader imprisoned for 27 years who became South Africa's first Black president (1994)."],
  ["8.7","Negritude Movement","Movement by French-speaking African and Caribbean writers celebrating Black culture and identity."],
  ["8.7","Liberation Theology","Catholic movement in Latin America emphasizing social justice for the poor."],
  ["8.8","Détente","Easing of Cold War tensions in the 1970s."],
  ["8.8","Mikhail Gorbachev","Last Soviet leader, whose reforms led to the end of the Cold War."],
  ["8.8","Perestroika","Gorbachev's economic restructuring policy."],
  ["8.8","Glasnost","Gorbachev's policy of openness, allowing more free speech."],
  ["8.8","Soviet-Afghan War","Costly Soviet war (1979–89) that weakened the USSR."],
  ["8.8","Solidarity","Polish labor union that led opposition to communist rule."],
  ["8.8","Fall of the Berlin Wall (1989)","Opening of the wall, a symbol of the collapse of communism in Eastern Europe."],
  ["8.8","Fall of the Soviet Union","The collapse of the USSR in 1991, ending the Cold War."]
],
9: [
  ["9.1","Globalization","The growing interconnection of the world's economies, cultures, and people through trade, technology, and communication."],
  ["9.1","Internet","Global computer network that transformed communication, commerce, and access to information."],
  ["9.1","Communication Revolution","Advances like radio, television, cell phones, and the internet that connected people across the globe."],
  ["9.1","Containerization","Shipping goods in standard metal containers, which made global trade much cheaper and faster."],
  ["9.1","Air Travel","Commercial jet flights that made global travel and trade faster."],
  ["9.1","Green Revolution","Agricultural advances (high-yield seeds, fertilizers, irrigation) that increased food production, especially in Asia and Latin America."],
  ["9.1","Commercial Agriculture","Large-scale farming for sale in global markets rather than for local consumption."],
  ["9.2","Antibiotics","Medicines such as penicillin that fight bacterial infections, dramatically lowering death rates."],
  ["9.2","Vaccines","Medicines that prevent diseases like polio; global vaccination eradicated smallpox by 1980."],
  ["9.2","Eradication of Smallpox","Global vaccination campaign that ended smallpox by 1980."],
  ["9.2","HIV/AIDS","Global pandemic from the 1980s, especially devastating in sub-Saharan Africa."],
  ["9.2","1918 Influenza Pandemic","Flu pandemic that killed tens of millions worldwide after WWI."],
  ["9.2","Diseases of Poverty","Diseases like malaria, tuberculosis, and cholera that remain common where medical care and sanitation are limited."],
  ["9.2","Diseases of Longevity","Diseases like heart disease and Alzheimer's that became more common as people lived longer."],
  ["9.2","Ebola","Deadly virus with outbreaks in Africa, especially the 2014 West Africa epidemic."],
  ["9.2","Life Expectancy","The average number of years people are expected to live, which rose dramatically in the 20th century."],
  ["9.3","Climate Change","Long-term warming of the Earth caused mainly by burning fossil fuels."],
  ["9.3","Greenhouse Gases","Gases like carbon dioxide and methane that trap heat in the atmosphere."],
  ["9.3","Deforestation","Clearing of forests for farming, logging, and development, as in the Amazon."],
  ["9.3","Desertification","Spread of desert conditions due to drought, overgrazing, and deforestation."],
  ["9.3","Kyoto Protocol (1997)","International agreement to reduce greenhouse gas emissions."],
  ["9.3","Paris Agreement (2015)","Global agreement to limit warming by reducing emissions."],
  ["9.4","Free-Market Economics","Economic policy that limits government regulation and promotes free trade and privatization."],
  ["9.4","Neoliberalism","Late-20th-century free-market policies promoted by Thatcher, Reagan, and international lenders."],
  ["9.4","Privatization","Selling state-owned businesses to private owners."],
  ["9.4","Deng Xiaoping","Chinese leader (1978–1992) whose market reforms opened China's economy while keeping Communist rule."],
  ["9.4","Special Economic Zones","Areas in China with free-market rules to attract foreign investment."],
  ["9.4","Asian Tigers","South Korea, Taiwan, Hong Kong, and Singapore, which industrialized rapidly through export-led growth."],
  ["9.4","Knowledge Economy","Economy based on information, technology, and services rather than manufacturing."],
  ["9.4","Outsourcing","Moving jobs to countries with cheaper labor."],
  ["9.4","Multinational Corporations","Companies operating in many countries, key drivers of globalization."],
  ["9.5","Universal Declaration of Human Rights (1948)","UN document setting out basic rights for all people."],
  ["9.5","Human Rights","Rights belonging to all people, which became a focus of international law and activism."],
  ["9.5","Feminism","Movements for women's equal rights, from voting to workplace equality."],
  ["9.5","Tiananmen Square (1989)","Pro-democracy protests in Beijing crushed by the Chinese military."],
  ["9.5","Green Belt Movement","Kenyan environmental movement founded by Wangari Maathai that planted millions of trees and empowered women."],
  ["9.5","Environmental Movement","Activism to protect the environment, like Greenpeace and Earth Day."],
  ["9.5","Anti-Apartheid Movement","Global campaign to end South African apartheid."],
  ["9.6","Global Culture","Shared culture spread worldwide through media and technology."],
  ["9.6","Consumerism","Culture focused on buying goods, spread globally by advertising and trade."],
  ["9.6","Bollywood","India's Hindi film industry, popular worldwide."],
  ["9.6","K-pop","South Korean pop music that became a global phenomenon."],
  ["9.6","Reggae","Jamaican music genre that spread worldwide, associated with Bob Marley."],
  ["9.6","Social Media","Online platforms for sharing content that spread culture and organized activism."],
  ["9.6","Global Sports","Events like the World Cup and Olympics that connect people worldwide."],
  ["9.7","Anti-Globalization Movement","Protests against global capitalism's effects on workers and the environment, like the 1999 WTO protests in Seattle."],
  ["9.7","Religious Fundamentalism","Movements seeking a return to strict religious principles, sometimes in reaction to globalization."],
  ["9.7","Terrorism","Using violence against civilians for political goals, like the 9/11 attacks by al-Qaeda."],
  ["9.7","World Social Forum","Annual meeting of groups opposing neoliberal globalization."],
  ["9.8","World Trade Organization (WTO)","International organization that sets rules for global trade."],
  ["9.8","NAFTA","North American Free Trade Agreement (1994) between the U.S., Canada, and Mexico."],
  ["9.8","European Union","Political and economic union of European countries with a common market and, for many members, the euro."],
  ["9.8","ASEAN","Association of Southeast Asian Nations, a regional economic and political group."],
  ["9.8","Mercosur","South American trade bloc."],
  ["9.8","International Monetary Fund (IMF)","Organization that lends to countries in financial trouble, often requiring free-market reforms."],
  ["9.8","World Bank","Organization that lends to developing countries for projects."],
  ["9.8","NGOs","Non-governmental organizations like Doctors Without Borders and Amnesty International that work on global issues."],
  ["9.8","Microfinance","Small loans to poor entrepreneurs, pioneered by the Grameen Bank in Bangladesh."]
]
};

/* Slug for a term's anchor (#g-slug). Duplicate terms within a unit get -2, -3... */
window.GLOSSARY_SLUG = function (s) {
  return String(s).normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()
    .replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
};
/* All of a unit's terms as objects: {topic, term, def, slug} */
window.GLOSSARY_LIST = function (n) {
  var seen = {};
  return (window.GLOSSARY[n] || []).map(function (r) {
    var s = window.GLOSSARY_SLUG(r[1]), k = s, i = 2;
    while (seen[k]) k = s + '-' + (i++);
    seen[k] = 1;
    return { topic: r[0], term: r[1], def: r[2], slug: k };
  });
};
